
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


//import ChatClient2;

/**
 *
 * @author Ricky K
 */
public class Login extends javax.swing.JFrame {
    public int benar = 0;
    private ArrayList<DataClient> users = new ArrayList<DataClient>();
    private DataSql client = new DataSql();
    
  
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //us_address.setVisible(false);
        //address.setVisible(false);
        btn_host.setVisible(false);
        
        String a = DB_MANAGER.getIP();
        us_address.setText(a);
        
        Object data[] = client.getAllData();
        for(int i=0;i<data.length;i++)
        {
            DataClient data1 = (DataClient) data[i];
            users.add(new DataClient(data1.getId(),data1.getPassword(),data1.getNama_barang(),data1.getKelamin(),data1.getStatus()));
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_host = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        us_name = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        us_password = new javax.swing.JPasswordField();
        b_send = new javax.swing.JButton();
        Username2 = new javax.swing.JLabel();
        us_address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();

        btn_host.setText("Set Host");
        btn_host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hostActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("Sign In");

        Username.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        Username.setText("Username");

        address.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        address.setText("Address");

        b_send.setText("Login");
        b_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sendActionPerformed(evt);
            }
        });

        Username2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        Username2.setText("Password");

        us_address.setEditable(false);
        us_address.setText("localhost");
        us_address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                us_addressMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel2.setText("Register Here");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel3.setText("Lupa Password ?");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group member free icon (1).png"))); // NOI18N

        Username1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Username1.setForeground(new java.awt.Color(255, 255, 255));
        Username1.setText("Authentication User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Username1)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(address)
                                    .addGap(156, 156, 156))
                                .addComponent(us_address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Username)
                                    .addGap(140, 140, 140))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(us_name, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(us_password, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Username2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(41, 41, 41))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(b_send, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(us_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Username2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(us_password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(us_address, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(b_send, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sendActionPerformed
        String User = us_name.getText();
        String Passi = String.valueOf(us_password.getPassword());
        int Pass = Integer.parseInt(Passi);
        int ada = 0;
        if(benar==0)
        {
            for(int i=0;i<users.size();i++)
            {
                String coba = users.get(i).getNama_barang();
                int pas = users.get(i).getPassword();
                int status = users.get(i).getStatus();
                //System.out.println(coba);
                //System.out.println(pas);
                if(User.equals(coba)&&Pass==pas)
                {
                    if(status==0)
                    {
                        client.updateStatus(1, coba);          
                        ada = 0;
                        ChatClient2 d = new ChatClient2();
                        d.setTitle("Single Chat");
                        d.usernameTextField.setText(us_name.getText());
                        d.portTextField.setText("2222");
                        d.serverTextField.setText(us_address.getText());
                        d.btn_masukiActionPerformed(evt);
                        if(users.get(i).getKelamin().equals("L"))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Silahkan Masuk Mr."+users.get(i).getNama_barang(),"Warning!!",JOptionPane.INFORMATION_MESSAGE);
                            d.User.setText("Mr. "+us_name.getText());
                            d.setVisible(true);
                            dispose();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, "Silahkan Masuk Ms."+users.get(i).getNama_barang(),"Warning!!",JOptionPane.INFORMATION_MESSAGE);
                            d.User.setText("Ms. "+us_name.getText());
                            d.setVisible(true);
                            dispose();
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Akun Anda Sedang Digunakan!!");
                    }
                    i=users.size();
                }
                else if(User.equals(coba))
                {
                    if(Pass!=pas)
                    {
                        ada = 1;
                    }
                    i = users.size();
                }
                else if(!User.equals(coba))
                {
                    ada = 2;
                   // JOptionPane.showMessageDialog(rootPane, "Username Anda Tidak Ada!!");
                }
                else
                {
                    ada = 3;
                }
            }
        }
        else
        {
            for(int i=0;i<users.size();i++)
            {
                String coba = users.get(i).getNama_barang();
                int pas = users.get(i).getPassword();
     
                if(User.equals(coba)&&Pass==pas)
                {
                    if(users.get(i).getStatus()==0)
                    {
                        client.updateStatus(1, coba);
                        JOptionPane.showMessageDialog(rootPane, "Silahkan Masuk Mr."+users.get(i).getNama_barang(),"Warning!!",JOptionPane.INFORMATION_MESSAGE);
                        ada = 0;
                        ChatClient d = new ChatClient();
                        d.setTitle("Multi Chat");
                        d.usernameTextField.setText(us_name.getText());
                        d.portTextField.setText("2222");
                        d.serverTextField.setText(us_address.getText());
                        d.btn_masukActionPerformed(evt);
                        if(users.get(i).getKelamin().equals("L"))
                        {
                            d.User.setText("Mr. "+us_name.getText());
                            d.setVisible(true);
                            dispose();
                        }
                        else
                        {
                            d.User.setText("Ms. "+us_name.getText());
                            d.setVisible(true);
                            dispose();
                        }
                        
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Akun Anda Sedang Digunakan!!");
                    }
                    i=users.size();
                    
                }
                else if(User.equals(coba))
                {
                    if(Pass!=pas)
                    {
                        ada = 1;
                    }
                    i = users.size();
                }
                else
                {
                    ada = 2;
                   // JOptionPane.showMessageDialog(rootPane, "Username Anda Tidak Ada!!");
                }
            }
//            ChatClient d = new ChatClient();
//            d.usernameTextField.setText(us_name.getText());
//            d.portTextField.setText("2222");
//            d.serverTextField.setText(us_address.getText());
//            d.btn_masukActionPerformed(evt);
//            d.User.setText("Mr. "+us_name.getText());
//            d.setVisible(true);
        }
        if(ada==1)
            JOptionPane.showMessageDialog(rootPane, "Password Anda Salah!!");
        else if(ada==2)
            JOptionPane.showMessageDialog(rootPane, "Username Anda Tidak Ada!!");
        //us_address.setVisible(true);
        //address.setVisible(true);
        //us_address.setText("localhost");
       // btn_host.setVisible(true);
        
    }//GEN-LAST:event_b_sendActionPerformed

    private void us_addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_us_addressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_us_addressMouseClicked

    private void btn_hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hostActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Register n = new Register();
        n.benar = benar;
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        LupaPassword n = new LupaPassword();
        n.benar = benar;
        n.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    public void getdatad()
    {
        Object data[] = client.getAllData();
            for(int i=0;i<data.length;i++)
            {
                DataClient data1 = (DataClient) data[i];
                users.add(new DataClient(data1.getId(),data1.getPassword(),data1.getNama_barang(),data1.getKelamin(),data1.getStatus()));
            }
    }
//    private class WorkerLoop extends SwingWorker<String,Void> {
//
//        @Override
//        protected String doInBackground() throws Exception {
//            Object data[] = client.getAllData();
//            for(int i=0;i<data.length;i++)
//            {
//                DataClient data1 = (DataClient) data[i];
//                users.add(new DataClient(data1.getId(),data1.getPassword(),data1.getNama_barang(),data1.getKelamin(),data1.getStatus()));
//            }
//            return "\nDone ...";
//        }
//
//        
//
//        
//    
//    }
//     private static class T implements Runnable {
// 
//        private Login e;
//
//        public T(Login e) {
//        this.e = e;
//        }
//        
//        @Override
//        public void run() {
//            while (true) {
//            if (e.isVisible()) {
//                // do the validation
//                    System.out.println("validation");
//                    getdata();
//                    try {
//                        Thread.sleep(1000);
//                    } catch (InterruptedException e1) {
//                        break;
//                    }
//                }
//            }
//        }
//        private void getdata()
//        {
//          Object data[] = client.getAllData();
//            for(int i=0;i<data.length;i++)
//            {
//                DataClient data1 = (DataClient) data[i];
//                users.add(new DataClient(data1.getId(),data1.getPassword(),data1.getNama_barang(),data1.getKelamin(),data1.getStatus()));
//            }
//        }
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
       //Login login = new Login();
       //new Thread(new loginf(login)).start();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Login().setVisible(true);
            }
        });
    }
//   public static class loginf extends Thread
//   {
//        private DataSql clientd;
//        private Login e;
//
//        public loginf(Login e) {
//            this.e = e;
//        }
//        
//        @Override
//       public void run() {
//            while (true) {
//            if (e.isVisible()) {
//                // do the validation
//                    System.out.println("validation");
//                    //getdata();
//                    try {
//                        Thread.sleep(1000);
//                    } catch (InterruptedException e1) {
//                        break;
//                    }
//                }
//            }
//        }
//       public static void getdata()
//       {
//           clientd = new DataSql();
//            Object data[] = clientd.getAllData();
//            for(int i=0;i<data.length;i++)
//            {
//                DataClient data1 = (DataClient) data[i];
//                users.add(new DataClient(data1.getId(),data1.getPassword(),data1.getNama_barang(),data1.getKelamin(),data1.getStatus()));
//            }
//       }
//   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JLabel Username2;
    private javax.swing.JLabel address;
    private javax.swing.JButton b_send;
    private javax.swing.JButton btn_host;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextField us_address;
    private javax.swing.JTextField us_name;
    private javax.swing.JPasswordField us_password;
    // End of variables declaration//GEN-END:variables

    private int parseInt(char[] password) {
        int hasil = parseInt(password);
        return hasil;
    }
}
